api:  
  build: ./
  ports: 
    - 3000:3000
  volumes:
    - ./butterfli-api:/go/src/github.com/hathbanger/butterfli-api
  links:
    - database
  environment:
    - DB_NAME=project

database:  
  image: mongo:3.0
  command: mongod --smallfiles --quiet --logpath=/dev/null