version: "3"
services:
  web:
    image: hathbanger/butterfli-api
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "1323:1323"
    networks:
      - webnet
  hello-mgo-mongo:
    image: mongo
networks:
  webnet: